# -*- coding: utf-8 -*-
"""Exoplant Habitability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIFh0te7xet5PBrj1dA0qiFipgIq7pjp

**MODULE 1: LOAD DATA**
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import os

df = pd.read_csv("//all_exoplanets_2021.csv")
print("Columns in DataFrame:", df.columns.tolist())

cols = [
    "Planet Name",
    "Mass",
    "Orbital Period Days",
    "Equilibrium Temperature",
    "Spectral Type",
    "Stellar Effective Temperature",
    "Stellar Mass",
    "Stellar Metallicity"
]

df = df[cols]
print("Data shape:", df.shape)
df.head()

"""CLEAN DATA & ONE-HOT-ENCODING"""

df.fillna(df.median(numeric_only=True), inplace=True)
if 'Spectral Type' in df.columns:
    df["Spectral Type"].fillna("Unknown", inplace=True)
    df = pd.get_dummies(df, columns=["Spectral Type"])

df.head()

"""**FEATURE ENGINEERING**"""

df["habitability_index"] = (
    (df["Equilibrium Temperature"].between(200, 350)).astype(int) +
    (df["Mass"] <= 10).astype(int)
)

df["stellar_index"] = (
    (df["Stellar Effective Temperature"].between(3000, 6000)).astype(int) +
    (df["Stellar Metallicity"] >= -0.5).astype(int)
)
df['stellar_index'] = df['stellar_index'].astype(int)
df['habitability_index'] = df['habitability_index'].astype(int)
df[['stellar_index','habitability_index']].head()

"""**NORMALIZATION**"""

scaler = MinMaxScaler()
num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = scaler.fit_transform(df[num_cols])

"""**SAVE CLEAN DATA**"""

os.makedirs("data", exist_ok=True)
df.to_csv("/content/exoplanets_cleaned.csv", index=False)
print("Clean dataset saved")

"""Module 3: Machine Learning Dataset Preparation"""

df["habitability_class"] = (df["habitability_index"] >= 0.5).astype(int)

# Drop non-numeric columns and the target variable
X = df.drop(["habitability_class", "Planet Name"], axis=1)
y = df["habitability_class"]

X_numeric = X.select_dtypes(include=np.number)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Select only numerical columns for correlation calculation
num_cols = df.select_dtypes(include=['number'])

# Calculate the correlation matrix
correlation_matrix = num_cols.corr()

# Display the correlation matrix using a heatmap for better visualization
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features')
plt.show()

"""**Select Features**


"""

#Calculate correlation with 'habitability_index' from the numeric subset
corr = X_numeric.corr()["habitability_index"].abs().sort_values(ascending=False)
selected_features = corr[corr > 0.2].index.tolist()

# Filter X to only include the selected numeric features
X = X[selected_features]

"""**Train–Test split sizes**"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

pipeline = Pipeline([
    ("scaler", StandardScaler())
])

X_train = pipeline.fit_transform(X_train)
X_test = pipeline.transform(X_test)

print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

!pip install gradio

import gradio as gr

def predict(radius, mass, period, temp, lum):
    return "Potentially Habitable"

gr.Interface(
    fn=predict,
    inputs=[
        gr.Number(label="Planet Radius"),
        gr.Number(label="Planet Mass"),
        gr.Number(label="Orbital Period"),
        gr.Number(label="Stellar Temperature"),
        gr.Number(label="Stellar Luminosity")
    ],
    outputs="text",
    title="🌍 Exoplanet Habitability Predictor"
).launch()

"""# New section"""